[package]
name = "lovely-ios"
version = "0.1.0"
edition = "2021"

[lib]
name = "lovely"
crate-type = ["cdylib"]

[dependencies]
lovely-core = { version ="0.7.1", path = "../lovely-core" }

once_cell = "1.19.0"
ctor = "0.2.7"

[build-dependencies]
cc = "1.2.10"
cmake = "0.1"

