[package]
name = "lovely-mac"
version = "0.1.0"
edition = "2021"

[lib]
name = "lovely"
crate-type = ["cdylib"]

[dependencies]
lovely-core = { version ="0.5.0-beta7", path = "../lovely-core" }

libc = "0.2.153"
once_cell = "1.19.0"
ctor = "0.2.7"

